"""Maintain AI_Course Markdown indexes and lightweight integrity checks."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[2]
COURSE_WEEKS = ROOT / "course" / "weeks"
MATERIALS_MARKDOWN = ROOT / "materials" / "markdown"
KNOWLEDGE = ROOT / "knowledge"

WEEK_TOPICS = {
    1: "课程导论与医药数据特征",
    2: "数据分析流程、复现规范与人机协作规范",
    3: "AI 辅助编程与 Python 快速入门",
    4: "R 基础语法、数据框操作与 AI 代码核验",
    5: "数据读取与整理",
    6: "缺失值、异常值处理与分组汇总",
    7: "描述统计与分布可视化",
    8: "统计推断基础",
    9: "相关分析与线性回归",
    10: "分类问题与逻辑回归",
    11: "科研图表规范与 SCI 图表表达",
    12: "高维数据与数学直觉",
    13: "PCA、聚类与热图",
    14: "转录组数据分析基础",
    15: "差异表达分析与功能解读",
    16: "单细胞转录组可视化",
    17: "综合项目工作坊：AI 协作分析与结果核验",
    18: "综合项目汇报与课程总结",
}

GENERATED_NOTICE = "<!-- Generated by scripts/maintenance/course_km_index.py; edit source files instead. -->"
FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*", re.S)
STATUS_RE = re.compile(r"(?:^|\s)(?:status[:/]\s*|status/)([A-Za-z0-9_-]+)", re.I)


class Issue(NamedTuple):
    code: str
    path: Path
    message: str


def rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def first_heading(text: str, fallback: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip() or fallback
    return fallback


def first_summary(text: str) -> str:
    body = FRONTMATTER_RE.sub("", text, count=1)
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        if stripped.startswith("!["):
            continue
        if stripped.startswith(("- ", "* ")):
            stripped = stripped[2:].strip()
        stripped = stripped.lstrip(">").strip()
        if stripped:
            return stripped[:140]
    return ""


def frontmatter_tags(frontmatter: str) -> list[str]:
    tags: list[str] = []
    in_tags_block = False
    for line in frontmatter.splitlines():
        stripped = line.strip()
        if stripped.startswith("tags:"):
            in_tags_block = True
            value = stripped.partition(":")[2].strip()
            if value.startswith("[") and value.endswith("]"):
                tags.extend(part.strip().strip("'\"") for part in value[1:-1].split(","))
            elif value:
                tags.append(value.strip("'\""))
            continue
        if in_tags_block:
            if line.startswith((" ", "\t")) and stripped.startswith("-"):
                tags.append(stripped[1:].strip().strip("'\""))
                continue
            break
    return [tag for tag in tags if tag]


def status_and_tags(path: Path, text: str, fallback_tags: list[str]) -> tuple[str, str]:
    status = "draft"
    if not first_summary(text):
        status = "needs-summary"
    status_match = STATUS_RE.search(text[:1200])
    if status_match:
        status = status_match.group(1)

    tags = list(fallback_tags)
    frontmatter = FRONTMATTER_RE.match(text)
    if frontmatter:
        tags.extend(frontmatter_tags(frontmatter.group(1)))
    match = re.search(r"week_(\d{2})", path.as_posix())
    if match:
        tags.append(f"week-{match.group(1)}")

    clean: list[str] = []
    for tag in tags:
        if tag and tag not in clean:
            clean.append(tag)
    return status, ", ".join(clean)


def markdown_files_under(root: Path, *, exclude_generated: bool = True) -> list[Path]:
    if not root.exists():
        return []
    files = sorted(root.rglob("*.md"), key=lambda p: p.relative_to(root).as_posix().lower())
    if exclude_generated:
        files = [p for p in files if p.name != "_index.md"]
    return files


def build_weeks_index(root: Path = ROOT) -> str:
    weeks_root = root / "course" / "weeks"
    lines = [
        "# Course Weeks Index",
        "",
        GENERATED_NOTICE,
        "",
        "| Week | Path | Topic | Summary | Status | Tags |",
        "|:---:|:---|:---|:---|:---|:---|",
    ]
    for week in range(1, 19):
        folder = weeks_root / f"week_{week:02d}"
        summary = ""
        status = "draft"
        tags = f"courseware, week-{week:02d}"
        for name in ("outline.md", "script.md", "materials.md"):
            candidate = folder / name
            if candidate.exists():
                text = read_text(candidate)
                summary = summary or first_summary(text)
                status, tags = status_and_tags(candidate, text, ["courseware", f"week-{week:02d}"])
        if not summary:
            summary = "status/needs-summary"
            status = "needs-summary"
        lines.append(
            f"| {week:02d} | [week_{week:02d}](week_{week:02d}/) | {WEEK_TOPICS[week]} | {summary} | {status} | {tags} |"
        )
    return "\n".join(lines) + "\n"


def build_markdown_tree_index(root: Path, title: str, base_tags: list[str]) -> str:
    lines = [
        f"# {title}",
        "",
        GENERATED_NOTICE,
        "",
        "| Path | Title | Summary | Status | Tags |",
        "|:---|:---|:---|:---|:---|",
    ]
    for file_path in markdown_files_under(root):
        text = read_text(file_path)
        path = file_path.relative_to(root).as_posix()
        status, tags = status_and_tags(file_path, text, base_tags)
        lines.append(
            f"| [{path}]({path}) | {first_heading(text, file_path.stem)} | {first_summary(text) or 'status/needs-summary'} | {status} | {tags} |"
        )
    return "\n".join(lines) + "\n"


def build_knowledge_indexes(root: Path = ROOT) -> dict[Path, str]:
    knowledge_root = root / "knowledge"
    indexes: dict[Path, str] = {}
    if not knowledge_root.exists():
        return indexes
    folders = sorted([p for p in knowledge_root.iterdir() if p.is_dir()], key=lambda p: p.name.lower())
    for folder in folders:
        indexes[folder / "_index.md"] = build_markdown_tree_index(
            folder,
            f"Knowledge {folder.name} Index",
            ["knowledge", folder.name],
        )
    return indexes


def expected_indexes(root: Path = ROOT) -> dict[Path, str]:
    indexes = {
        root / "course" / "weeks" / "_index.md": build_weeks_index(root),
        root / "materials" / "markdown" / "_index.md": build_markdown_tree_index(
            root / "materials" / "markdown",
            "Materials Markdown Index",
            ["materials", "markdown"],
        ),
    }
    indexes.update(build_knowledge_indexes(root))
    return indexes


def check_index_files(indexes: dict[Path, str]) -> list[Issue]:
    issues: list[Issue] = []
    for path, expected in indexes.items():
        if not path.exists():
            issues.append(Issue("MISSING_INDEX", path, "Index file is missing"))
            continue
        if read_text(path) != expected:
            issues.append(Issue("OUTDATED_INDEX", path, "Index file differs from generated content"))
    return issues


def write_index_files(indexes: dict[Path, str]) -> None:
    for path, content in indexes.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def strip_markdown_code(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return re.sub(r"`[^`\n]+`", "", text)


def iter_markdown_link_targets(text: str) -> list[str]:
    targets: list[str] = []
    text = strip_markdown_code(text)
    index = 0
    while index < len(text):
        start = text.find("[", index)
        if start == -1:
            break
        if start > 0 and text[start - 1] == "!":
            index = start + 1
            continue
        label_end = text.find("](", start)
        if label_end == -1 or "\n" in text[start:label_end]:
            index = start + 1
            continue
        cursor = label_end + 2
        target_start = cursor
        depth = 1
        while cursor < len(text):
            char = text[cursor]
            if char == "\\":
                cursor += 2
                continue
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    targets.append(text[target_start:cursor])
                    cursor += 1
                    break
            cursor += 1
        index = cursor
    return targets


def markdown_link_target(file_path: Path, raw_target: str) -> Path | None:
    target = raw_target.strip().strip("<>")
    if not target or target.startswith("#"):
        return None
    if re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target):
        return None
    target = target.split("#", 1)[0].split("?", 1)[0].strip()
    if not target:
        return None
    return (file_path.parent / unquote(target)).resolve()


def find_broken_links(root: Path, files: list[Path]) -> list[Issue]:
    issues: list[Issue] = []
    root_resolved = root.resolve()
    for file_path in files:
        for raw_target in iter_markdown_link_targets(read_text(file_path)):
            target = markdown_link_target(file_path, raw_target)
            if target is None:
                continue
            try:
                target.relative_to(root_resolved)
            except ValueError:
                continue
            if not target.exists():
                issues.append(Issue("BROKEN_LINK", file_path, f"Missing target: {raw_target}"))
    return issues


def checked_markdown_files(root: Path = ROOT) -> list[Path]:
    roots = [
        root / "AGENTS.md",
        root / "README.md",
        root / "memory.md",
        root / "course",
        root / "docs",
        root / "knowledge",
        root / "materials" / "markdown",
    ]
    files: list[Path] = []
    for item in roots:
        if item.is_file():
            files.append(item)
        elif item.is_dir():
            files.extend(markdown_files_under(item, exclude_generated=False))
    return sorted(set(files), key=lambda p: p.relative_to(root).as_posix().lower())


def check_week_topic_alignment(root: Path = ROOT) -> list[Issue]:
    issues: list[Issue] = []
    week11 = root / "course" / "weeks" / "week_11"
    week15 = root / "course" / "weeks" / "week_15"
    week11_text = "\n".join(read_text(p) for p in sorted(week11.glob("*.md")) if p.exists())
    week15_text = "\n".join(read_text(p) for p in sorted(week15.glob("*.md")) if p.exists())
    if "科研图表" not in week11_text and "SCI 图表" not in week11_text:
        issues.append(Issue("STALE_WEEK_MAPPING", week11, "Week 11 should be SCI figure expression, not DESeq2"))
    stale_terms = ["DESeq2", "差异表达", "富集分析"]
    heading_lines = "\n".join(line for line in week11_text.splitlines() if line.lstrip().startswith("#"))
    if any(term in heading_lines for term in stale_terms):
        issues.append(Issue("STALE_WEEK_MAPPING", week11, "Week 11 headings still look like differential-expression content"))
    if "差异表达" not in week15_text:
        issues.append(Issue("STALE_WEEK_MAPPING", week15, "Week 15 should contain differential-expression content"))
    return issues


def run_check(root: Path = ROOT) -> list[Issue]:
    issues = check_index_files(expected_indexes(root))
    issues.extend(find_broken_links(root, checked_markdown_files(root)))
    issues.extend(check_week_topic_alignment(root))
    return issues


def print_issues(issues: list[Issue]) -> None:
    if not issues:
        print("OK: indexes, Markdown links, and Week 11/15 alignment are current.")
        return
    for issue in issues:
        try:
            path = rel(issue.path)
        except ValueError:
            path = str(issue.path)
        print(f"{issue.code}: {path}: {issue.message}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check indexes and links without changing files.")
    parser.add_argument("--write", action="store_true", help="Regenerate project-local index files, then check.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.check and not args.write:
        parser.error("Choose --check or --write")
    if args.write:
        write_index_files(expected_indexes(ROOT))
    issues = run_check(ROOT)
    print_issues(issues)
    return 1 if issues else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
